const collegeData = [
  {
    college_name: "Tech University",
    location: "New York, USA",
    fees: 35000,
    college_dunia_rating: 8,
    user_rating: 7.5,
    featured: true,
    year_established: 1920,
  },
  {
    college_name: "Global Institute of Science",
    location: "London, UK",
    fees: 25000,
    college_dunia_rating: 7,
    user_rating: 6.5,
    featured: false,
    year_established: 1955,
  },
  {
    college_name: "Eastern College",
    location: "Tokyo, Japan",
    fees: 22000,
    college_dunia_rating: 4,
    user_rating: 8.0,
    featured: true,
    year_established: 1880,
  },
  {
    college_name: "Green Valley University",
    location: "Sydney, Australia",
    fees: 30000,
    college_dunia_rating: 3,
    user_rating: 7.9,
    featured: false,
    year_established: 1978,
  },
  {
    college_name: "Central Institute of Arts",
    location: "Paris, France",
    fees: 28000,
    college_dunia_rating: 2,
    user_rating: 7.0,
    featured: true,
    year_established: 1905,
  },
  {
    college_name: "Northern State University",
    location: "Toronto, Canada",
    fees: 27000,
    college_dunia_rating: 1,
    user_rating: 7.8,
    featured: true,
    year_established: 1925,
  },
  {
    college_name: "Western Business College",
    location: "Los Angeles, USA",
    fees: 33000,
    college_dunia_rating: 9,
    user_rating: 7.1,
    featured: false,
    year_established: 1985,
  },
  {
    college_name: "Southern Technical Institute",
    location: "Atlanta, USA",
    fees: 26000,
    college_dunia_rating: 7.5,
    user_rating: 7.0,
    featured: false,
    year_established: 1990,
  },
  {
    college_name: "East Coast University",
    location: "Boston, USA",
    fees: 32000,
    college_dunia_rating: 8.2,
    user_rating: 7.4,
    featured: false,
    year_established: 1902,
  },
  {
    college_name: "Oceanview Institute",
    location: "Miami, USA",
    fees: 29000,
    college_dunia_rating: 7.9,
    user_rating: 6.9,
    featured: true,
    year_established: 1975,
  },
  {
    college_name: "Central Medical College",
    location: "Chicago, USA",
    fees: 28000,
    college_dunia_rating: 8.1,
    user_rating: 7.5,
    featured: true,
    year_established: 1980,
  },
  {
    college_name: "Mountainview Polytechnic",
    location: "Denver, USA",
    fees: 31000,
    college_dunia_rating: 7.7,
    user_rating: 7.2,
    featured: false,
    year_established: 1985,
  },
  {
    college_name: "Pacific Coast University",
    location: "San Francisco, USA",
    fees: 34000,
    college_dunia_rating: 8.4,
    user_rating: 7.6,
    featured: true,
    year_established: 1930,
  },
  {
    college_name: "Desert Ridge College",
    location: "Phoenix, USA",
    fees: 27000,
    college_dunia_rating: 7.3,
    user_rating: 7.0,
    featured: false,
    year_established: 1988,
  },
  {
    college_name: "Lakeside College of Technology",
    location: "Seattle, USA",
    fees: 31500,
    college_dunia_rating: 8.2,
    user_rating: 7.5,
    featured: true,
    year_established: 1950,
  },
  {
    college_name: "Capitol City University",
    location: "Washington D.C., USA",
    fees: 31000,
    college_dunia_rating: 7.8,
    user_rating: 7.1,
    featured: false,
    year_established: 1940,
  },
  {
    college_name: "West Coast Academy",
    location: "Los Angeles, USA",
    fees: 35000,
    college_dunia_rating: 8.6,
    user_rating: 7.4,
    featured: true,
    year_established: 1910,
  },
  {
    college_name: "Coastal Institute",
    location: "San Diego, USA",
    fees: 28000,
    college_dunia_rating: 8.0,
    user_rating: 7.3,
    featured: true,
    year_established: 1945,
  },
  {
    college_name: "Midwest College",
    location: "Kansas City, USA",
    fees: 30000,
    college_dunia_rating: 8.3,
    user_rating: 7.6,
    featured: false,
    year_established: 1935,
  },
  {
    college_name: "Northern Lights University",
    location: "Anchorage, Alaska, USA",
    fees: 26000,
    college_dunia_rating: 7.5,
    user_rating: 7.0,
    featured: false,
    year_established: 1975,
  },
  {
    college_name: "Capital Institute of Arts",
    location: "Berlin, Germany",
    fees: 27000,
    college_dunia_rating: 8.5,
    user_rating: 7.7,
    featured: true,
    year_established: 1900,
  },
  {
    college_name: "North Sea Polytechnic",
    location: "Oslo, Norway",
    fees: 28000,
    college_dunia_rating: 8.3,
    user_rating: 7.5,
    featured: false,
    year_established: 1920,
  },
  {
    college_name: "Highland College",
    location: "Edinburgh, Scotland",
    fees: 29000,
    college_dunia_rating: 8.4,
    user_rating: 7.8,
    featured: true,
    year_established: 1885,
  },
];

export default collegeData;
